apiVersion: v1
kind: Service
metadata:
  name: wangamy
  labels:
    app: wangamy
spec:
  type: NodePort
  selector:
    app: wangamy
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30001
